apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: deploy-verification-demo-app-run-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: verify-staging
    profiles: []
    strategy:
      standard:
        verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: verify-staging
description: staging Run service
run:
  location: projects/tolstoy-staffing-23032/locations/us-central1
